#pylint:disable=invalid-name
"""empty message

#Revision ID: 28aab50ce595_
Revises:
Create Date: 2024-08-17 12:00:59.618016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28aab50ce595' #pylint:disable=invalid-name
down_revision = None #pylint:disable=invalid-name
branch_labels = None #pylint:disable=invalid-name
depends_on = None #pylint:disable=invalid-name


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',#pylint:disable=no-member
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('post',#pylint:disable=no-member
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')#pylint:disable=no-member
    op.drop_table('user')#pylint:disable=no-member
    # ### end Alembic commands ###
